components:
  messages:
    profileProducts:
      payload:
          type: object
          properties:
            profile:
              id: 
                type: integer
            products: 
              type: string
