components:
  messages:
    profileProducts:
      payload:
          type: object
          properties:
            profile:
              type: object
              properties:
                id: 
                  type: integer
            products: 
              type: integer
